### ISSUE TITLE
Getting error when users attempt to sign up!

### ISSUE THREAD

**Issue by laurenierullo** [RailsApps/rails-stripe-membership-saas#109]
I get this error:

No such plan: silver; a similar object exists in test mode, but a live mode key was used to make this request..

Please help!

**Comment by kathyonu** [comment]
coderawal, i will try to answer your questions:
1. the app does create the plan for the customer when they choose the plan they want to subscribe to, using the home page.  the app does create the plans, so to speak, they are called roles.
2. yes, the developer needs to go to stripe.com, and create their test plans, for their application to use.
3. the user, the public person using your app on the net, does not do such a thing. they sign up on app.
4. if customer/subscriber does not have sufficient funds in account during any recurring period, 
  stripe.com will try again, according to the timetable you set, using your stripe dashboard. we
  have ours set so that after three attempts to charge the account, we stop trying and the customer
   sits in limbo .. we ourselves have not yet addressed the matter of having our one such customer
   do what is required to begin subscribing again .. which is what she will have to do.  when we are 
  ready, codes wise, we will ask her to arrive on our sign up page and sign up and we will both see 
  what happens.  also, you can know that the next evolution of rails-stripe-membership-saas will not
  use the 'roles' table, it will be much simplified by using <code> enum </code> as the holder of roles.
  If you follow the ongoing output of Daniel's apps and tutorials, you can see how he has changed the
  setting up of roles, thankfully. So look for  <code> enum </code> in the next evolution coming soon.
  If you want to create customers, with their plans in place, so that you can easily work with 
  them in development, i proffer our db/seeds.rb file from our working app, solely for use in 
  development, it generates your users with their plans. 
<code> 

puts "ROLES"
YAML.load(ENV['ROLES']).each do |role|
    Role.find_or_create_by(:name => role)
  puts 'role: ' << role
end

puts "DEFAULT USERS"
user = User.find_or_create_by(:email => ENV['ADMIN_EMAIL'].dup) do |user|
    user.name = ENV['ADMIN_NAME'].dup
    user.password = ENV['ADMIN_PASSWORD'].dup
    user.password_confirmation = ENV['ADMIN_PASSWORD'].dup
end
user.add_role :admin
puts 'user: ' << user.name

user2 = User.find_or_create_by(:email => 'user2@example.com') do |user|
    user.name = 'Silver User'
    user.password = 'changemenow'
    user.password_confirmation = 'changemenow'
end
user2.add_role :silver
puts 'user: ' << user.name

user3 = User.find_or_create_by(:email => 'user3@example.com') do |user|
    user.name = 'Gold User'
    user.password = 'changemenow'
    user.password_confirmation = 'changemenow'
end
user3.add_role :gold
puts 'user: ' << user.name

user4 = User.find_or_create_by(:email => 'user4@example.com') do |user|
    user.name = 'Platinum User'
    user.password = 'changemenow'
    user.password_confirmation = 'changemenow'
end
user4.add_role :platinum
puts 'user: ' << user.name

user5 = User.find_or_create_by(:email => 'user5@example.com') do |user|
    user.name = 'Visitor User'
    user.password = 'changemenow'
    user.password_confirmation = 'changemenow'
end
user5.add_role :visitor
puts 'user: ' << user.name

puts "users: #{user2.name}, #{user3.name}, #{user4.name}, #{user5.name}"
 </code>

**Comment by coderawal** [comment]
Thanks Kathyonu, now it's clear.

**Comment by DanielKehoe** [comment]
There is a new version of this application for Rails 4.2 using the Payola gem.
