### ISSUE TITLE
Will rails-stripe-membership-saas run on Ruby 2.3.3 and Rails 5 ?

### ISSUE THREAD

**Issue by ghost** [RailsApps/rails-stripe-membership-saas#165]
Is anyone running this?
If so, any problems?

**Comment by DanielKehoe** [comment]
I haven't updated the example application for Rails 5. I'm no longer supporting the application.

**Comment by ghost** [comment]
Will you be creating a new similar subscription application or just done with it?
And are you not updating any of your existing apps? 
Taking a different roadmap now or what?


Mark

**Comment by DanielKehoe** [comment]
I've updated all the other RailsApps example applications to Rails 5 and will continue to maintain them. However, several users have been unhappy with the Payola gem, because of complexity and inconsistent support. I recommend using the https://github.com/RailsApps/rails-stripe-coupons application as a basis for a subscription application.

**Comment by ghost** [comment]
Excellent, good to know. Thx. 

Mark
